version: '3.4'

services:
  db:
    restart: always
    container_name: decide_db
    image: postgres:10.15-alpine
    networks:
      - decide
    environment:
        - POSTGRES_PASSWORD=postgres
  web:
    restart: always
    container_name: decide_web
    image: decide_web:latest
    build: .
    command: ash -c "python manage.py migrate && gunicorn -w 5 decide.wsgi --timeout=500 -b 0.0.0.0:5000"
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - decide
  nginx:
    restart: always
    container_name: decide_nginx
    image: decide_nginx:latest
    build:
        context: .
        dockerfile: Dockerfile-nginx
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - decide

networks:
  decide:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
